volumes:
  db:
  mangosd_etc:
  realmd_etc:

services:
  db:
    image: linuxserver/mariadb:latest
    container_name: cmangos-db
    environment:
      TZ: Europe/London
      MYSQL_ROOT_PASSWORD: mangos
      MYSQL_MAX_CONNECTIONS: 500
      MYSQL_INNODB_BUFFER_POOL_SIZE: 1G
      MYSQL_INNODB_LOG_FILE_SIZE: 256M
      MYSQL_INNODB_FLUSH_METHOD: O_DIRECT
      # Add these for connection stability
      MYSQL_WAIT_TIMEOUT: 28800
      MYSQL_INTERACTIVE_TIMEOUT: 28800
      MYSQL_MAX_ALLOWED_PACKET: 128M
    volumes:
      - db:/var/lib/mysql
      - "./db:/config"
      #- "./db:/etc/mysql/conf.d"
    networks:
      - mangosbot-network
    ports:
      - 33307:3306
    restart: unless-stopped
    healthcheck:
      test: 
        - "CMD"
        - "/usr/bin/mysqladmin"
        - "ping"
        - "-h"
        - "localhost"
        - "-u"
        - "root"
        - "-p$$MYSQL_ROOT_PASSWORD"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
        
  mangosd:
    # build:
    #   context: .
    #   dockerfile: ./mangosd/Dockerfile
    #   args:
    #     - BUILD_PLAYERBOT=ON
    #     - BUILD_AHBOT=ON
    image: angercraft/mangosbot-mangosd
    container_name: cmangos-classic-mangosd
    networks:
      - mangosbot-network
    ports:
      - 8085:8085
      - 3443:3443 # Remote Console
      # - 7878:7878 # Enable if you want to use SOAP   
    volumes:
      - "./config:/opt/cmangos/etc"
      - "./logs:/opt/cmangos/logs"
      - "./data:/opt/cmangos/data"
      - "./scripts:/opt/cmangos/scripts"
      - "./backup:/opt/cmangos/backup"
      - "./sql:/opt/cmangos/sql"
      - "./bin:/opt/cmangos/bin"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    stop_grace_period: 30m # The amount of seconds to wait before killing the container forcefully (if the server has a lot of bots is recommended to increase this)
    environment:
      PUID: 1028
      PGID: 65537
      TZ: Europe/London
      CHARACTERS_DB: classiccharacters
      MANGOSD_DB: classicmangos
      REALMD_DB: classicrealmd
      PLAYERBOTS_DB: classicplayerbots
      DB_SERVER: cmangos-db
      DB_ROOT_USER: root
      DB_ROOT_PASS: mangos
      DB_PORT: 3306
      DB_USER: mangos
      DB_PASS: mangos
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    depends_on:
      db:
        condition: service_healthy

  realmd:
    # build:
    #   context: .
    #   dockerfile: ./realmd/Dockerfile
    image: angercraft/mangosbot-realmd
    container_name: cmangos-classic-realmd
    networks:
      - mangosbot-network
    ports:
      - 3724:3724
    volumes:
      - "./config:/opt/cmangos/etc"
      - "./logs:/opt/cmangos/logs"
      - "./bin:/opt/cmangos/bin"
      - "./scripts:/opt/cmangos/scripts"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
    environment:
      PUID: 1028
      PGID: 65537
      TZ: Europe/London
      REALMD_DB: classicrealmd
      DB_USER: mangos
      DB_PASS: mangos
      DB_SERVER: cmangos-db
      DB_PORT: 3306

networks:
  mangosbot-network:
    name: mangosbot-network
    driver: bridge
