name: Build and Push MangosBot Images

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  MANGOSD_IMAGE_NAME: mangosbot-mangosd
  REALMD_IMAGE_NAME: mangosbot-realmd
  VERSION: ${{ github.event.release.tag_name || 'latest' }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      mangosd_tags: ${{ steps.meta-mangosd.outputs.tags }}
      mangosd_labels: ${{ steps.meta-mangosd.outputs.labels }}
      realmd_tags: ${{ steps.meta-realmd.outputs.tags }}
      realmd_labels: ${{ steps.meta-realmd.outputs.labels }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for MangosD
        id: meta-mangosd
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ env.MANGOSD_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: Extract metadata for RealmD
        id: meta-realmd
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USERNAME }}/${{ env.REALMD_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

  build-realmd:
    name: Build and Push RealmD Image
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push RealmD image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./realmd/Dockerfile
          push: true
          tags: ${{ needs.setup.outputs.realmd_tags }}
          labels: ${{ needs.setup.outputs.realmd_labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-mangosd:
    name: Build and Push MangosD Image
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push MangosD image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mangosd/Dockerfile
          build-args: BUILD_PLAYERBOT=ON BUILD_AHBOT=ON
          push: true
          tags: ${{ needs.setup.outputs.mangosd_tags }}
          labels: ${{ needs.setup.outputs.mangosd_labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [build-realmd, build-mangosd]
    steps:
      - name: Discord notification - Success
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#43b581"
          username: "GitHub Actions"
          message: |
            🚀 **New Release Build Successful!**

            **Release:** ${{ github.event.release.tag_name || 'manual build' }}
            **Release Title:** ${{ github.event.release.name || 'Manual Build' }}

            **Images Built:**
            • MangosD: `${{ env.DOCKERHUB_USERNAME }}/${{ env.MANGOSD_IMAGE_NAME }}:${{ env.VERSION }}`
            • RealmD: `${{ env.DOCKERHUB_USERNAME }}/${{ env.REALMD_IMAGE_NAME }}:${{ env.VERSION }}`

            **Build Link:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Discord notification - Failure
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#ff0000"
          username: "GitHub Actions"
          message: |
            ❌ **Release Build Failed!**

            **Release:** ${{ github.event.release.tag_name || 'manual build' }}
            **Release Title:** ${{ github.event.release.name || 'Manual Build' }}

            **Error Details:**
            Please check the build logs for more information.

            **Build Link:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
